server:
  port: 9050
spring:
  application:
    name: order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: localhost:9010
order:
  cron-expression: 0/5 * * * * ?